# Generated by Django 3.2.8 on 2021-10-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211030_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='released',
            new_name='releasedDate',
        ),
    ]
