# Generated by Django 3.2.8 on 2021-10-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_released_movie_releaseddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releasedDate',
            new_name='released_date',
        ),
    ]
