# Generated by Django 3.2.8 on 2021-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_releaseddate_movie_released_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(),
        ),
    ]
